### ISSUE TITLE
how did you deal with twitter preventing write actions?

### ISSUE THREAD

**Issue by sckott** [richardwestenra/mensdaybot#1]
on slide 19 http://richardwestenra.com/mensdaybot-talk/#/19 you mentioned the bot being restricted from performing write actions. How did you sort that out?

**Comment by richardwestenra** [comment]
Hi @sckott. Unfortunately I didn't sort it out: It happened the day after International Women's Day so I considered the bot out of action and haven't tried to resurrect it since. If I'd intended to keep using the bot then I'd probably have tried again with a new twitter account. 

Hope this helps! If you need any further help feel free to message me on [twitter](http://twitter.com/richardwestenra) or [send me an email](mailto:richard@richardwestenra.com).

**Comment by sckott** [comment]
okay, thx
